# Generated by Django 5.0.7 on 2024-07-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='name',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
